### ISSUE TITLE
X-UA-Compatible Header doesn't validate

### ISSUE THREAD

**Issue by gebeer** [nternetinspired/OneWeb#1]
Hello,

If I uncomment line 104 in logic.php
$doc->setMetaData( 'X-UA-Compatible', 'IE=edge;chrome=1' );

I get a validation error on W3C Validator.

Would be better to move this in the .htaccess file, like this
  <IfModule mod_headers.c>
    Header append Cache-Control "public"
    Header set X-UA-Compatible "IE=edge;chrome=1"
  </IfModule>

**Comment by nternetinspired** [comment]
The issue is that not everyone can and will use (or even see) an .htaccess file. 

For me, disabling compatibility mode is preferable to a validation error and I take html5bp's lead on this: https://github.com/h5bp/html5-boilerplate/blob/master/doc/html.md#x-ua-compatible

I also take the view, expressed eloquently here by Paul Irish https://groups.google.com/forum/#!msg/html5boilerplate/bRtrFSrKjtI/AOa44To23nMJ, that we shouldn't be too concerned about this breaking validation.
